"""
Configuration module: entities, indicators, era ranges, and region mappings.

This module is imported by all other modules (wb_api, fetch_data, build_deck).
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Entities
# ---------------------------------------------------------------------------
ENTITIES: list[dict] = [
    # --- Regions (7) ---
    {
        "name": "World",
        "entity_type": "region",
        "wb_code": "WLD",
        "tag_slug": "world",
    },
    {
        "name": "Sub-Saharan Africa",
        "entity_type": "region",
        "wb_code": "SSF",
        "tag_slug": "sub_saharan_africa",
    },
    {
        "name": "South Asia",
        "entity_type": "region",
        "wb_code": "SAS",
        "tag_slug": "south_asia",
    },
    {
        "name": "East Asia & Pacific",
        "entity_type": "region",
        "wb_code": "EAS",
        "tag_slug": "east_asia_pacific",
    },
    {
        "name": "Latin America & Caribbean",
        "entity_type": "region",
        "wb_code": "LCN",
        "tag_slug": "latin_america_caribbean",
    },
    {
        "name": "Middle East & North Africa",
        "entity_type": "region",
        "wb_code": "MEA",
        "tag_slug": "middle_east_north_africa",
    },
    {
        "name": "Europe & Central Asia",
        "entity_type": "region",
        "wb_code": "ECS",
        "tag_slug": "europe_central_asia",
    },
    # --- Major Economies (15) ---
    {
        "name": "USA",
        "entity_type": "major",
        "region": "Europe & Central Asia",
        "iso3": "USA",
        "tag_slug": "usa",
    },
    {
        "name": "China",
        "entity_type": "major",
        "region": "East Asia & Pacific",
        "iso3": "CHN",
        "tag_slug": "china",
    },
    {
        "name": "India",
        "entity_type": "major",
        "region": "South Asia",
        "iso3": "IND",
        "tag_slug": "india",
    },
    {
        "name": "Japan",
        "entity_type": "major",
        "region": "East Asia & Pacific",
        "iso3": "JPN",
        "tag_slug": "japan",
    },
    {
        "name": "Germany",
        "entity_type": "major",
        "region": "Europe & Central Asia",
        "iso3": "DEU",
        "tag_slug": "germany",
    },
    {
        "name": "UK",
        "entity_type": "major",
        "region": "Europe & Central Asia",
        "iso3": "GBR",
        "tag_slug": "uk",
    },
    {
        "name": "France",
        "entity_type": "major",
        "region": "Europe & Central Asia",
        "iso3": "FRA",
        "tag_slug": "france",
    },
    {
        "name": "Brazil",
        "entity_type": "major",
        "region": "Latin America & Caribbean",
        "iso3": "BRA",
        "tag_slug": "brazil",
    },
    {
        "name": "Indonesia",
        "entity_type": "major",
        "region": "East Asia & Pacific",
        "iso3": "IDN",
        "tag_slug": "indonesia",
    },
    {
        "name": "Russia",
        "entity_type": "major",
        "region": "Europe & Central Asia",
        "iso3": "RUS",
        "tag_slug": "russia",
    },
    {
        "name": "Mexico",
        "entity_type": "major",
        "region": "Latin America & Caribbean",
        "iso3": "MEX",
        "tag_slug": "mexico",
    },
    {
        "name": "South Korea",
        "entity_type": "major",
        "region": "East Asia & Pacific",
        "iso3": "KOR",
        "tag_slug": "south_korea",
    },
    {
        "name": "Turkey",
        "entity_type": "major",
        "region": "Europe & Central Asia",
        "iso3": "TUR",
        "tag_slug": "turkey",
    },
    {
        "name": "Nigeria",
        "entity_type": "major",
        "region": "Sub-Saharan Africa",
        "iso3": "NGA",
        "tag_slug": "nigeria",
    },
    {
        "name": "Saudi Arabia",
        "entity_type": "major",
        "region": "Middle East & North Africa",
        "iso3": "SAU",
        "tag_slug": "saudi_arabia",
    },
    # --- Long-Tail (25) ---
    {
        "name": "Bangladesh",
        "entity_type": "long_tail",
        "region": "South Asia",
        "iso3": "BGD",
        "tag_slug": "bangladesh",
    },
    {
        "name": "Vietnam",
        "entity_type": "long_tail",
        "region": "East Asia & Pacific",
        "iso3": "VNM",
        "tag_slug": "vietnam",
    },
    {
        "name": "Ethiopia",
        "entity_type": "long_tail",
        "region": "Sub-Saharan Africa",
        "iso3": "ETH",
        "tag_slug": "ethiopia",
    },
    {
        "name": "Kenya",
        "entity_type": "long_tail",
        "region": "Sub-Saharan Africa",
        "iso3": "KEN",
        "tag_slug": "kenya",
    },
    {
        "name": "Ghana",
        "entity_type": "long_tail",
        "region": "Sub-Saharan Africa",
        "iso3": "GHA",
        "tag_slug": "ghana",
    },
    {
        "name": "Tanzania",
        "entity_type": "long_tail",
        "region": "Sub-Saharan Africa",
        "iso3": "TZA",
        "tag_slug": "tanzania",
    },
    {
        "name": "Egypt",
        "entity_type": "long_tail",
        "region": "Middle East & North Africa",
        "iso3": "EGY",
        "tag_slug": "egypt",
    },
    {
        "name": "Pakistan",
        "entity_type": "long_tail",
        "region": "South Asia",
        "iso3": "PAK",
        "tag_slug": "pakistan",
    },
    {
        "name": "Philippines",
        "entity_type": "long_tail",
        "region": "East Asia & Pacific",
        "iso3": "PHL",
        "tag_slug": "philippines",
    },
    {
        "name": "Thailand",
        "entity_type": "long_tail",
        "region": "East Asia & Pacific",
        "iso3": "THA",
        "tag_slug": "thailand",
    },
    {
        "name": "Colombia",
        "entity_type": "long_tail",
        "region": "Latin America & Caribbean",
        "iso3": "COL",
        "tag_slug": "colombia",
    },
    {
        "name": "Argentina",
        "entity_type": "long_tail",
        "region": "Latin America & Caribbean",
        "iso3": "ARG",
        "tag_slug": "argentina",
    },
    {
        "name": "Chile",
        "entity_type": "long_tail",
        "region": "Latin America & Caribbean",
        "iso3": "CHL",
        "tag_slug": "chile",
    },
    {
        "name": "South Africa",
        "entity_type": "long_tail",
        "region": "Sub-Saharan Africa",
        "iso3": "ZAF",
        "tag_slug": "south_africa",
    },
    {
        "name": "Poland",
        "entity_type": "long_tail",
        "region": "Europe & Central Asia",
        "iso3": "POL",
        "tag_slug": "poland",
    },
    {
        "name": "Ukraine",
        "entity_type": "long_tail",
        "region": "Europe & Central Asia",
        "iso3": "UKR",
        "tag_slug": "ukraine",
    },
    {
        "name": "Iran",
        "entity_type": "long_tail",
        "region": "Middle East & North Africa",
        "iso3": "IRN",
        "tag_slug": "iran",
    },
    {
        "name": "Iraq",
        "entity_type": "long_tail",
        "region": "Middle East & North Africa",
        "iso3": "IRQ",
        "tag_slug": "iraq",
    },
    {
        "name": "Malaysia",
        "entity_type": "long_tail",
        "region": "East Asia & Pacific",
        "iso3": "MYS",
        "tag_slug": "malaysia",
    },
    {
        "name": "Myanmar",
        "entity_type": "long_tail",
        "region": "East Asia & Pacific",
        "iso3": "MMR",
        "tag_slug": "myanmar",
    },
    {
        "name": "DR Congo",
        "entity_type": "long_tail",
        "region": "Sub-Saharan Africa",
        "iso3": "COD",
        "tag_slug": "dr_congo",
    },
    {
        "name": "Mozambique",
        "entity_type": "long_tail",
        "region": "Sub-Saharan Africa",
        "iso3": "MOZ",
        "tag_slug": "mozambique",
    },
    {
        "name": "Rwanda",
        "entity_type": "long_tail",
        "region": "Sub-Saharan Africa",
        "iso3": "RWA",
        "tag_slug": "rwanda",
    },
    {
        "name": "Cambodia",
        "entity_type": "long_tail",
        "region": "East Asia & Pacific",
        "iso3": "KHM",
        "tag_slug": "cambodia",
    },
    {
        "name": "Bolivia",
        "entity_type": "long_tail",
        "region": "Latin America & Caribbean",
        "iso3": "BOL",
        "tag_slug": "bolivia",
    },
]

# ---------------------------------------------------------------------------
# REGIONS: convenience subset of ENTITIES
# ---------------------------------------------------------------------------
REGIONS: list[dict] = [e for e in ENTITIES if e["entity_type"] == "region"]

# ---------------------------------------------------------------------------
# Urban Entities (GHS-UCDB top 50 by 2025 population)
# ---------------------------------------------------------------------------
URBAN_ENTITIES: list[dict] = [
    # --- Aggregate references ---
    {"name": "All Cities", "entity_type": "aggregate", "tag_slug": "all_cities"},
    {"name": "High income", "entity_type": "aggregate", "tag_slug": "high_income"},
    {"name": "Upper Middle", "entity_type": "aggregate", "tag_slug": "upper_middle"},
    {"name": "Lower Middle", "entity_type": "aggregate", "tag_slug": "lower_middle"},
    {"name": "Low income", "entity_type": "aggregate", "tag_slug": "low_income"},
    # --- Cities (50) ---
    {"uc_id": 10933, "name": "Guangzhou", "entity_type": "city", "country": "China", "income_group": "Upper Middle", "tag_slug": "guangzhou"},
    {"uc_id": 5472, "name": "Jakarta", "entity_type": "city", "country": "Indonesia", "income_group": "Upper Middle", "tag_slug": "jakarta"},
    {"uc_id": 6090, "name": "Dhaka", "entity_type": "city", "country": "Bangladesh", "income_group": "Lower Middle", "tag_slug": "dhaka"},
    {"uc_id": 5929, "name": "Tokyo", "entity_type": "city", "country": "Japan", "income_group": "High income", "tag_slug": "tokyo"},
    {"uc_id": 7963, "name": "New Delhi", "entity_type": "city", "country": "India", "income_group": "Lower Middle", "tag_slug": "new_delhi"},
    {"uc_id": 11345, "name": "Shanghai", "entity_type": "city", "country": "China", "income_group": "Upper Middle", "tag_slug": "shanghai"},
    {"uc_id": 2323, "name": "Manila", "entity_type": "city", "country": "Philippines", "income_group": "Lower Middle", "tag_slug": "manila"},
    {"uc_id": 4605, "name": "Cairo", "entity_type": "city", "country": "Egypt", "income_group": "Lower Middle", "tag_slug": "cairo"},
    {"uc_id": 11352, "name": "Kolkata", "entity_type": "city", "country": "India", "income_group": "Lower Middle", "tag_slug": "kolkata"},
    {"uc_id": 348, "name": "Seoul", "entity_type": "city", "country": "South Korea", "income_group": "High income", "tag_slug": "seoul"},
    {"uc_id": 2457, "name": "Karachi", "entity_type": "city", "country": "Pakistan", "income_group": "Lower Middle", "tag_slug": "karachi"},
    {"uc_id": 7599, "name": "Mumbai", "entity_type": "city", "country": "India", "income_group": "Lower Middle", "tag_slug": "mumbai"},
    {"uc_id": 7277, "name": "São Paulo", "entity_type": "city", "country": "Brazil", "income_group": "Upper Middle", "tag_slug": "sao_paulo"},
    {"uc_id": 2315, "name": "Bangkok", "entity_type": "city", "country": "Thailand", "income_group": "Upper Middle", "tag_slug": "bangkok"},
    {"uc_id": 8745, "name": "Beijing", "entity_type": "city", "country": "China", "income_group": "Upper Middle", "tag_slug": "beijing"},
    {"uc_id": 5402, "name": "Mexico City", "entity_type": "city", "country": "México", "income_group": "Upper Middle", "tag_slug": "mexico_city"},
    {"uc_id": 9558, "name": "Bengaluru", "entity_type": "city", "country": "India", "income_group": "Lower Middle", "tag_slug": "bengaluru"},
    {"uc_id": 5239, "name": "Ho Chi Minh City", "entity_type": "city", "country": "Vietnam", "income_group": "Lower Middle", "tag_slug": "ho_chi_minh_city"},
    {"uc_id": 2576, "name": "Moscow", "entity_type": "city", "country": "Russia", "income_group": "Upper Middle", "tag_slug": "moscow"},
    {"uc_id": 7794, "name": "Lahore", "entity_type": "city", "country": "Pakistan", "income_group": "Lower Middle", "tag_slug": "lahore"},
    {"uc_id": 2637, "name": "Istanbul", "entity_type": "city", "country": "Turkey", "income_group": "Upper Middle", "tag_slug": "istanbul"},
    {"uc_id": 8099, "name": "New York City", "entity_type": "city", "country": "United States", "income_group": "High income", "tag_slug": "new_york_city"},
    {"uc_id": 4443, "name": "Buenos Aires", "entity_type": "city", "country": "Argentina", "income_group": "Upper Middle", "tag_slug": "buenos_aires"},
    {"uc_id": 2007, "name": "Los Angeles", "entity_type": "city", "country": "United States", "income_group": "High income", "tag_slug": "los_angeles"},
    {"uc_id": 1876, "name": "Kinshasa", "entity_type": "city", "country": "Democratic Republic of the Congo", "income_group": "Low income", "tag_slug": "kinshasa"},
    {"uc_id": 1289, "name": "Lagos", "entity_type": "city", "country": "Nigeria", "income_group": "Lower Middle", "tag_slug": "lagos"},
    {"uc_id": 4399, "name": "Osaka", "entity_type": "city", "country": "Japan", "income_group": "High income", "tag_slug": "osaka"},
    {"uc_id": 1082, "name": "Luanda", "entity_type": "city", "country": "Angola", "income_group": "Lower Middle", "tag_slug": "luanda"},
    {"uc_id": 11199, "name": "Suzhou", "entity_type": "city", "country": "China", "income_group": "Upper Middle", "tag_slug": "suzhou"},
    {"uc_id": 10300, "name": "Chennai", "entity_type": "city", "country": "India", "income_group": "Lower Middle", "tag_slug": "chennai"},
    {"uc_id": 2171, "name": "Lima", "entity_type": "city", "country": "Peru", "income_group": "Upper Middle", "tag_slug": "lima"},
    {"uc_id": 11407, "name": "Shantou", "entity_type": "city", "country": "China", "income_group": "Upper Middle", "tag_slug": "shantou"},
    {"uc_id": 3881, "name": "Bogota", "entity_type": "city", "country": "Colombia", "income_group": "Upper Middle", "tag_slug": "bogota"},
    {"uc_id": 5816, "name": "London", "entity_type": "city", "country": "United Kingdom", "income_group": "High income", "tag_slug": "london"},
    {"uc_id": 7799, "name": "Rio de Janeiro", "entity_type": "city", "country": "Brazil", "income_group": "Upper Middle", "tag_slug": "rio_de_janeiro"},
    {"uc_id": 10576, "name": "Hajipur", "entity_type": "city", "country": "India", "income_group": "Lower Middle", "tag_slug": "hajipur"},
    {"uc_id": 1142, "name": "Taipei", "entity_type": "city", "country": "Taiwan", "income_group": "High income", "tag_slug": "taipei"},
    {"uc_id": 9524, "name": "Hyderabad", "entity_type": "city", "country": "India", "income_group": "Lower Middle", "tag_slug": "hyderabad"},
    {"uc_id": 5174, "name": "Tehran", "entity_type": "city", "country": "Iran", "income_group": "Lower Middle", "tag_slug": "tehran"},
    {"uc_id": 2878, "name": "Paris", "entity_type": "city", "country": "France", "income_group": "High income", "tag_slug": "paris"},
    {"uc_id": 3570, "name": "Dar es-Salaam", "entity_type": "city", "country": "Tanzania", "income_group": "Lower Middle", "tag_slug": "dar_es_salaam"},
    {"uc_id": 5748, "name": "Bandung", "entity_type": "city", "country": "Indonesia", "income_group": "Upper Middle", "tag_slug": "bandung"},
    {"uc_id": 3512, "name": "Johannesburg", "entity_type": "city", "country": "South Africa", "income_group": "Upper Middle", "tag_slug": "johannesburg"},
    {"uc_id": 8557, "name": "Chongqing", "entity_type": "city", "country": "China", "income_group": "Upper Middle", "tag_slug": "chongqing"},
    {"uc_id": 1648, "name": "Kuala Lumpur", "entity_type": "city", "country": "Malaysia", "income_group": "Upper Middle", "tag_slug": "kuala_lumpur"},
    {"uc_id": 10131, "name": "Wuhan", "entity_type": "city", "country": "China", "income_group": "Upper Middle", "tag_slug": "wuhan"},
    {"uc_id": 10887, "name": "Nanjing", "entity_type": "city", "country": "China", "income_group": "Upper Middle", "tag_slug": "nanjing"},
    {"uc_id": 3026, "name": "Riyadh", "entity_type": "city", "country": "Saudi Arabia", "income_group": "High income", "tag_slug": "riyadh"},
    {"uc_id": 6143, "name": "Ahmedabad", "entity_type": "city", "country": "India", "income_group": "Lower Middle", "tag_slug": "ahmedabad"},
    {"uc_id": 5213, "name": "Nagoya", "entity_type": "city", "country": "Japan", "income_group": "High income", "tag_slug": "nagoya"},
]

# ---------------------------------------------------------------------------
# DECKS registry
# ---------------------------------------------------------------------------
DECKS: dict[str, dict] = {
    "development": {
        "name": "Knowledge Base::Global Development Indicators",
        "deck_id": 2026032300,
        "output": "knowledge_base_development.apkg",
        "data_dir": "data/development",
        "era_ranges": {
            "1960": (1955, 1965, 1960),
            "1990": (1988, 1992, 1990),
            "current": (2020, 2026, 2026),
        },
        "indicators": [
            {
                "id": "gdp_pc_ppp",
                "name": "GDP per capita (PPP)",
                "category": "development",
                "unit_label": "in 2021 international dollars",
                "wb_code": "NY.GDP.PCAP.PP.KD",
                "decimals": 0,
                "unit_prefix": "$",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "poverty_headcount",
                "name": "Poverty headcount ratio",
                "category": "development",
                "unit_label": "% of population below $3.00/day (2021 PPP)",
                "wb_code": "SI.POV.DDAY",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "gini",
                "name": "Gini coefficient",
                "category": "development",
                "unit_label": "(0–100 scale)",
                "wb_code": "SI.POV.GINI",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": False,
            },
            {
                "id": "trade_pct_gdp",
                "name": "Trade as % of GDP",
                "category": "development",
                "unit_label": "% of GDP",
                "wb_code": "NE.TRD.GNFS.ZS",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "life_expectancy",
                "name": "Life expectancy at birth",
                "category": "health",
                "unit_label": "in years",
                "wb_code": "SP.DYN.LE00.IN",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "under5_mortality",
                "name": "Under-5 mortality rate",
                "category": "health",
                "unit_label": "deaths per 1,000 live births",
                "wb_code": "SH.DYN.MORT",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "maternal_mortality",
                "name": "Maternal mortality ratio",
                "category": "health",
                "unit_label": "deaths per 100,000 live births",
                "wb_code": "SH.STA.MMRT",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "fertility_rate",
                "name": "Total fertility rate",
                "category": "health",
                "unit_label": "births per woman",
                "wb_code": "SP.DYN.TFRT.IN",
                "decimals": 2,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "co2_per_capita",
                "name": "CO2 emissions per capita",
                "category": "energy",
                "unit_label": "tonnes CO2e per capita",
                "wb_code": "EN.GHG.CO2.PC.CE.AR5",
                "decimals": 2,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "renewable_electricity",
                "name": "Renewable share of electricity",
                "category": "energy",
                "unit_label": "% of total electricity output",
                "wb_code": "EG.ELC.RNEW.ZS",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "energy_intensity",
                "name": "Energy intensity of GDP",
                "category": "energy",
                "unit_label": "MJ per $2021 PPP GDP",
                "wb_code": "EG.EGY.PRIM.PP.KD",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "population",
                "name": "Population",
                "category": "geography",
                "unit_label": "millions",
                "wb_code": "SP.POP.TOTL",
                "decimals": 0,
                "unit_prefix": "",
                "scale_factor": 1_000_000,
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "land_area",
                "name": "Land area",
                "category": "geography",
                "unit_label": "km²",
                "wb_code": "AG.LND.TOTL.K2",
                "decimals": 0,
                "unit_prefix": "",
                "time_invariant": True,
                "current_only": False,
                "has_regional_aggregates": True,
            },
        ],
    },
    "tech_adoption": {
        "name": "Knowledge Base::Technology Adoption",
        "deck_id": 2026032301,
        "output": "knowledge_base_tech_adoption.apkg",
        "data_dir": "data/tech_adoption",
        "era_ranges": {
            "1990": (1988, 1992, 1990),
            "2000": (1998, 2002, 2000),
            "2010": (2008, 2012, 2010),
            "current": (2020, 2026, 2026),
        },
        "indicators": [
            {
                "id": "internet_users",
                "name": "Internet users",
                "category": "technology",
                "unit_label": "% of population",
                "wb_code": "IT.NET.USER.ZS",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "mobile_subscriptions",
                "name": "Mobile cellular subscriptions",
                "category": "technology",
                "unit_label": "per 100 people",
                "wb_code": "IT.CEL.SETS.P2",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "broadband",
                "name": "Fixed broadband subscriptions",
                "category": "technology",
                "unit_label": "per 100 people",
                "wb_code": "IT.NET.BBND.P2",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "rd_expenditure",
                "name": "R&D expenditure",
                "category": "technology",
                "unit_label": "% of GDP",
                "wb_code": "GB.XPD.RSDV.GD.ZS",
                "decimals": 2,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "hightech_exports",
                "name": "High-technology exports",
                "category": "technology",
                "unit_label": "% of manufactured exports",
                "wb_code": "TX.VAL.TECH.MF.ZS",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "electricity_access",
                "name": "Electricity access",
                "category": "technology",
                "unit_label": "% of population",
                "wb_code": "EG.ELC.ACCS.ZS",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
        ],
    },
    "conflict_security": {
        "name": "Knowledge Base::Conflict & Security",
        "deck_id": 2026032302,
        "output": "knowledge_base_conflict_security.apkg",
        "data_dir": "data/conflict_security",
        "era_ranges": {
            "1960": (1955, 1965, 1960),
            "1990": (1988, 1992, 1990),
            "current": (2020, 2026, 2026),
        },
        "indicators": [
            {
                "id": "mil_expenditure_gdp",
                "name": "Military expenditure",
                "category": "military",
                "unit_label": "% of GDP",
                "wb_code": "MS.MIL.XPND.GD.ZS",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "mil_expenditure_usd",
                "name": "Military expenditure",
                "category": "military",
                "unit_label": "billions of current US$",
                "wb_code": "MS.MIL.XPND.CD",
                "decimals": 1,
                "unit_prefix": "",
                "scale_factor": 1_000_000_000,
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "armed_forces",
                "name": "Armed forces personnel",
                "category": "military",
                "unit_label": "thousands",
                "wb_code": "MS.MIL.TOTL.P1",
                "decimals": 0,
                "unit_prefix": "",
                "scale_factor": 1_000,
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "arms_imports",
                "name": "Arms imports",
                "category": "military",
                "unit_label": "millions (constant 1990 US$)",
                "wb_code": "MS.MIL.MPRT.KD",
                "decimals": 0,
                "unit_prefix": "",
                "scale_factor": 1_000_000,
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "homicides",
                "name": "Intentional homicides",
                "category": "security",
                "unit_label": "per 100,000 people",
                "wb_code": "VC.IHR.PSRC.P5",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "refugees_origin",
                "name": "Refugees by country of origin",
                "category": "security",
                "unit_label": "thousands",
                "wb_code": "SM.POP.RHCR.EO",
                "decimals": 0,
                "unit_prefix": "",
                "scale_factor": 1_000,
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "refugees_asylum",
                "name": "Refugees by country of asylum",
                "category": "security",
                "unit_label": "thousands",
                "wb_code": "SM.POP.RHCR.EA",
                "decimals": 0,
                "unit_prefix": "",
                "scale_factor": 1_000,
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
        ],
    },
    "finance": {
        "name": "Knowledge Base::Finance & Markets",
        "deck_id": 2026032303,
        "output": "knowledge_base_finance.apkg",
        "data_dir": "data/finance",
        "era_ranges": {
            "1960": (1955, 1965, 1960),
            "1990": (1988, 1992, 1990),
            "current": (2020, 2026, 2026),
        },
        "indicators": [
            {
                "id": "inflation",
                "name": "Inflation (CPI)",
                "category": "macro",
                "unit_label": "annual %",
                "wb_code": "FP.CPI.TOTL.ZG",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "current_account",
                "name": "Current account balance",
                "category": "macro",
                "unit_label": "% of GDP",
                "wb_code": "BN.CAB.XOKA.GD.ZS",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": False,
            },
            {
                "id": "reserves",
                "name": "Total reserves including gold",
                "category": "macro",
                "unit_label": "billions of current US$",
                "wb_code": "FI.RES.TOTL.CD",
                "decimals": 1,
                "unit_prefix": "",
                "scale_factor": 1_000_000_000,
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": False,
            },
            {
                "id": "real_interest_rate",
                "name": "Real interest rate",
                "category": "macro",
                "unit_label": "%",
                "wb_code": "FR.INR.RINR",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": False,
            },
            {
                "id": "market_cap",
                "name": "Market capitalization",
                "category": "financial_system",
                "unit_label": "% of GDP",
                "wb_code": "CM.MKT.LCAP.GD.ZS",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "stocks_traded",
                "name": "Stocks traded",
                "category": "financial_system",
                "unit_label": "% of GDP",
                "wb_code": "CM.MKT.TRAD.GD.ZS",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "domestic_credit",
                "name": "Domestic credit to private sector",
                "category": "financial_system",
                "unit_label": "% of GDP",
                "wb_code": "FS.AST.PRVT.GD.ZS",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "remittances",
                "name": "Personal remittances received",
                "category": "financial_system",
                "unit_label": "billions of current US$",
                "wb_code": "BX.TRF.PWKR.CD.DT",
                "decimals": 1,
                "unit_prefix": "",
                "scale_factor": 1_000_000_000,
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
        ],
    },
    "education": {
        "name": "Knowledge Base::Education",
        "deck_id": 2026032806,
        "output": "knowledge_base_education.apkg",
        "data_dir": "data/education",
        "era_ranges": {
            "1990": (1988, 1992, 1990),
            "current": (2020, 2026, 2026),
        },
        "indicators": [
            {
                "id": "adult_literacy",
                "name": "Adult literacy rate",
                "category": "education",
                "unit_label": "% of people ages 15+",
                "wb_code": "SE.ADT.LITR.ZS",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "secondary_enrollment",
                "name": "Secondary school enrollment",
                "category": "education",
                "unit_label": "% gross",
                "wb_code": "SE.SEC.ENRR",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "tertiary_enrollment",
                "name": "Tertiary school enrollment",
                "category": "education",
                "unit_label": "% gross",
                "wb_code": "SE.TER.ENRR",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "education_expenditure",
                "name": "Government education expenditure",
                "category": "education",
                "unit_label": "% of GDP",
                "wb_code": "SE.XPD.TOTL.GD.ZS",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
        ],
    },
    "urban_areas": {
        "name": "Knowledge Base::Urban Areas",
        "deck_id": 2026032604,
        "output": "knowledge_base_urban_areas.apkg",
        "data_dir": "data/urban_areas",
        "gpkg_path": "resources/OECD/GHS_UCDB_GLOBE_R2024A_V1_1/GHS_UCDB_GLOBE_R2024A.gpkg",
        "entities": URBAN_ENTITIES,
        "reference_entity": "All Cities",
        "reference_entity_type": "aggregate",
        "era_ranges": {
            "1990": (1990, 1990, 1990),
            "2000": (2000, 2000, 2000),
            "2010": (2010, 2010, 2010),
            "2020": (2020, 2020, 2020),
            "2025": (2025, 2025, 2025),
        },
        "indicators": [
            {
                "id": "population",
                "name": "Population",
                "category": "demographics",
                "unit_label": "millions",
                "ghsl_table": "GHSL",
                "ghsl_column": "GH_POP_TOT",
                "decimals": 1,
                "unit_prefix": "",
                "scale_factor": 1_000_000,
                "years": [1990, 2000, 2010, 2020, 2025],
            },
            {
                "id": "co2_per_capita",
                "name": "CO2 emissions per capita",
                "category": "emissions",
                "unit_label": "tonnes per person",
                "ghsl_table": "EMISSIONS",
                "ghsl_column": "EM_CO2_PEC",
                "decimals": 2,
                "unit_prefix": "",
                "scale_factor": 1,
                "years": [1990, 2000, 2010, 2020],
            },
            {
                "id": "pm25_concentration",
                "name": "PM2.5 concentration",
                "category": "emissions",
                "unit_label": "\u00b5g/m\u00b3",
                "ghsl_table": "EMISSIONS",
                "ghsl_column": "EM_PM2_CON",
                "decimals": 1,
                "unit_prefix": "",
                "scale_factor": 1,
                "years": [2000, 2010, 2020],
            },
            {
                "id": "life_expectancy",
                "name": "Life expectancy",
                "category": "socioeconomic",
                "unit_label": "years",
                "ghsl_table": "SOCIOECONOMIC",
                "ghsl_column": "SC_SEC_LET",
                "decimals": 1,
                "unit_prefix": "",
                "scale_factor": 1,
                "years": [1990, 2000, 2010, 2020],
            },
            {
                "id": "built_up_per_capita",
                "name": "Built-up area per capita",
                "category": "urban_form",
                "unit_label": "m\u00b2 per person",
                "ghsl_table": "GHSL",
                "ghsl_column": "GH_BPC_TOT",
                "decimals": 1,
                "unit_prefix": "",
                "scale_factor": 1,
                "years": [1990, 2000, 2010, 2020, 2025],
            },
            {
                "id": "hdi",
                "name": "Human Development Index",
                "category": "socioeconomic",
                "unit_label": "index (0\u20131)",
                "ghsl_table": "SOCIOECONOMIC",
                "ghsl_column": "SC_SEC_HDI",
                "decimals": 3,
                "unit_prefix": "",
                "scale_factor": 1,
                "years": [1990, 2000, 2010, 2020],
            },
        ],
    },
    "descriptive_stats": {
        "name": "Knowledge Base::Descriptive Statistics",
        "deck_id": 2026032605,
        "output": "knowledge_base_descriptive_stats.apkg",
        "data_dir": "data/descriptive_stats",
        "source_decks": ["development", "tech_adoption", "conflict_security", "finance", "urban_areas"],
    },
}
