"""
Configuration module: entities, indicators, era ranges, and region mappings.

This module is imported by all other modules (wb_api, fetch_data, build_deck).
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Entities
# ---------------------------------------------------------------------------
ENTITIES: list[dict] = [
    # --- Regions (7) ---
    {
        "name": "World",
        "entity_type": "region",
        "wb_code": "WLD",
        "tag_slug": "world",
    },
    {
        "name": "Sub-Saharan Africa",
        "entity_type": "region",
        "wb_code": "SSF",
        "tag_slug": "sub_saharan_africa",
    },
    {
        "name": "South Asia",
        "entity_type": "region",
        "wb_code": "SAS",
        "tag_slug": "south_asia",
    },
    {
        "name": "East Asia & Pacific",
        "entity_type": "region",
        "wb_code": "EAS",
        "tag_slug": "east_asia_pacific",
    },
    {
        "name": "Latin America & Caribbean",
        "entity_type": "region",
        "wb_code": "LCN",
        "tag_slug": "latin_america_caribbean",
    },
    {
        "name": "Middle East & North Africa",
        "entity_type": "region",
        "wb_code": "MEA",
        "tag_slug": "middle_east_north_africa",
    },
    {
        "name": "Europe & Central Asia",
        "entity_type": "region",
        "wb_code": "ECS",
        "tag_slug": "europe_central_asia",
    },
    # --- Major Economies (15) ---
    {
        "name": "USA",
        "entity_type": "major",
        "region": "Europe & Central Asia",
        "iso3": "USA",
        "tag_slug": "usa",
    },
    {
        "name": "China",
        "entity_type": "major",
        "region": "East Asia & Pacific",
        "iso3": "CHN",
        "tag_slug": "china",
    },
    {
        "name": "India",
        "entity_type": "major",
        "region": "South Asia",
        "iso3": "IND",
        "tag_slug": "india",
    },
    {
        "name": "Japan",
        "entity_type": "major",
        "region": "East Asia & Pacific",
        "iso3": "JPN",
        "tag_slug": "japan",
    },
    {
        "name": "Germany",
        "entity_type": "major",
        "region": "Europe & Central Asia",
        "iso3": "DEU",
        "tag_slug": "germany",
    },
    {
        "name": "UK",
        "entity_type": "major",
        "region": "Europe & Central Asia",
        "iso3": "GBR",
        "tag_slug": "uk",
    },
    {
        "name": "France",
        "entity_type": "major",
        "region": "Europe & Central Asia",
        "iso3": "FRA",
        "tag_slug": "france",
    },
    {
        "name": "Brazil",
        "entity_type": "major",
        "region": "Latin America & Caribbean",
        "iso3": "BRA",
        "tag_slug": "brazil",
    },
    {
        "name": "Indonesia",
        "entity_type": "major",
        "region": "East Asia & Pacific",
        "iso3": "IDN",
        "tag_slug": "indonesia",
    },
    {
        "name": "Russia",
        "entity_type": "major",
        "region": "Europe & Central Asia",
        "iso3": "RUS",
        "tag_slug": "russia",
    },
    {
        "name": "Mexico",
        "entity_type": "major",
        "region": "Latin America & Caribbean",
        "iso3": "MEX",
        "tag_slug": "mexico",
    },
    {
        "name": "South Korea",
        "entity_type": "major",
        "region": "East Asia & Pacific",
        "iso3": "KOR",
        "tag_slug": "south_korea",
    },
    {
        "name": "Turkey",
        "entity_type": "major",
        "region": "Europe & Central Asia",
        "iso3": "TUR",
        "tag_slug": "turkey",
    },
    {
        "name": "Nigeria",
        "entity_type": "major",
        "region": "Sub-Saharan Africa",
        "iso3": "NGA",
        "tag_slug": "nigeria",
    },
    {
        "name": "Saudi Arabia",
        "entity_type": "major",
        "region": "Middle East & North Africa",
        "iso3": "SAU",
        "tag_slug": "saudi_arabia",
    },
    # --- Long-Tail (25) ---
    {
        "name": "Bangladesh",
        "entity_type": "long_tail",
        "region": "South Asia",
        "iso3": "BGD",
        "tag_slug": "bangladesh",
    },
    {
        "name": "Vietnam",
        "entity_type": "long_tail",
        "region": "East Asia & Pacific",
        "iso3": "VNM",
        "tag_slug": "vietnam",
    },
    {
        "name": "Ethiopia",
        "entity_type": "long_tail",
        "region": "Sub-Saharan Africa",
        "iso3": "ETH",
        "tag_slug": "ethiopia",
    },
    {
        "name": "Kenya",
        "entity_type": "long_tail",
        "region": "Sub-Saharan Africa",
        "iso3": "KEN",
        "tag_slug": "kenya",
    },
    {
        "name": "Ghana",
        "entity_type": "long_tail",
        "region": "Sub-Saharan Africa",
        "iso3": "GHA",
        "tag_slug": "ghana",
    },
    {
        "name": "Tanzania",
        "entity_type": "long_tail",
        "region": "Sub-Saharan Africa",
        "iso3": "TZA",
        "tag_slug": "tanzania",
    },
    {
        "name": "Egypt",
        "entity_type": "long_tail",
        "region": "Middle East & North Africa",
        "iso3": "EGY",
        "tag_slug": "egypt",
    },
    {
        "name": "Pakistan",
        "entity_type": "long_tail",
        "region": "South Asia",
        "iso3": "PAK",
        "tag_slug": "pakistan",
    },
    {
        "name": "Philippines",
        "entity_type": "long_tail",
        "region": "East Asia & Pacific",
        "iso3": "PHL",
        "tag_slug": "philippines",
    },
    {
        "name": "Thailand",
        "entity_type": "long_tail",
        "region": "East Asia & Pacific",
        "iso3": "THA",
        "tag_slug": "thailand",
    },
    {
        "name": "Colombia",
        "entity_type": "long_tail",
        "region": "Latin America & Caribbean",
        "iso3": "COL",
        "tag_slug": "colombia",
    },
    {
        "name": "Argentina",
        "entity_type": "long_tail",
        "region": "Latin America & Caribbean",
        "iso3": "ARG",
        "tag_slug": "argentina",
    },
    {
        "name": "Chile",
        "entity_type": "long_tail",
        "region": "Latin America & Caribbean",
        "iso3": "CHL",
        "tag_slug": "chile",
    },
    {
        "name": "South Africa",
        "entity_type": "long_tail",
        "region": "Sub-Saharan Africa",
        "iso3": "ZAF",
        "tag_slug": "south_africa",
    },
    {
        "name": "Poland",
        "entity_type": "long_tail",
        "region": "Europe & Central Asia",
        "iso3": "POL",
        "tag_slug": "poland",
    },
    {
        "name": "Ukraine",
        "entity_type": "long_tail",
        "region": "Europe & Central Asia",
        "iso3": "UKR",
        "tag_slug": "ukraine",
    },
    {
        "name": "Iran",
        "entity_type": "long_tail",
        "region": "Middle East & North Africa",
        "iso3": "IRN",
        "tag_slug": "iran",
    },
    {
        "name": "Iraq",
        "entity_type": "long_tail",
        "region": "Middle East & North Africa",
        "iso3": "IRQ",
        "tag_slug": "iraq",
    },
    {
        "name": "Malaysia",
        "entity_type": "long_tail",
        "region": "East Asia & Pacific",
        "iso3": "MYS",
        "tag_slug": "malaysia",
    },
    {
        "name": "Myanmar",
        "entity_type": "long_tail",
        "region": "East Asia & Pacific",
        "iso3": "MMR",
        "tag_slug": "myanmar",
    },
    {
        "name": "DR Congo",
        "entity_type": "long_tail",
        "region": "Sub-Saharan Africa",
        "iso3": "COD",
        "tag_slug": "dr_congo",
    },
    {
        "name": "Mozambique",
        "entity_type": "long_tail",
        "region": "Sub-Saharan Africa",
        "iso3": "MOZ",
        "tag_slug": "mozambique",
    },
    {
        "name": "Rwanda",
        "entity_type": "long_tail",
        "region": "Sub-Saharan Africa",
        "iso3": "RWA",
        "tag_slug": "rwanda",
    },
    {
        "name": "Cambodia",
        "entity_type": "long_tail",
        "region": "East Asia & Pacific",
        "iso3": "KHM",
        "tag_slug": "cambodia",
    },
    {
        "name": "Bolivia",
        "entity_type": "long_tail",
        "region": "Latin America & Caribbean",
        "iso3": "BOL",
        "tag_slug": "bolivia",
    },
]

# ---------------------------------------------------------------------------
# REGIONS: convenience subset of ENTITIES
# ---------------------------------------------------------------------------
REGIONS: list[dict] = [e for e in ENTITIES if e["entity_type"] == "region"]

# ---------------------------------------------------------------------------
# DECKS registry
# ---------------------------------------------------------------------------
DECKS: dict[str, dict] = {
    "development": {
        "name": "Knowledge Base::Global Development Indicators",
        "deck_id": 2026032300,
        "output": "knowledge_base.apkg",
        "data_dir": "data/development",
        "era_ranges": {
            "1960": (1955, 1965, 1960),
            "1990": (1988, 1992, 1990),
            "current": (2020, 2026, 2026),
        },
        "indicators": [
            {
                "id": "gdp_pc_ppp",
                "name": "GDP per capita (PPP)",
                "category": "development",
                "unit_label": "in 2021 international dollars",
                "wb_code": "NY.GDP.PCAP.PP.KD",
                "decimals": 0,
                "unit_prefix": "$",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "poverty_headcount",
                "name": "Poverty headcount ratio",
                "category": "development",
                "unit_label": "% of population below $3.00/day (2021 PPP)",
                "wb_code": "SI.POV.DDAY",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "gini",
                "name": "Gini coefficient",
                "category": "development",
                "unit_label": "(0–100 scale)",
                "wb_code": "SI.POV.GINI",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": False,
            },
            {
                "id": "trade_pct_gdp",
                "name": "Trade as % of GDP",
                "category": "development",
                "unit_label": "% of GDP",
                "wb_code": "NE.TRD.GNFS.ZS",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "life_expectancy",
                "name": "Life expectancy at birth",
                "category": "health",
                "unit_label": "in years",
                "wb_code": "SP.DYN.LE00.IN",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "under5_mortality",
                "name": "Under-5 mortality rate",
                "category": "health",
                "unit_label": "deaths per 1,000 live births",
                "wb_code": "SH.DYN.MORT",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "maternal_mortality",
                "name": "Maternal mortality ratio",
                "category": "health",
                "unit_label": "deaths per 100,000 live births",
                "wb_code": "SH.STA.MMRT",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "fertility_rate",
                "name": "Total fertility rate",
                "category": "health",
                "unit_label": "births per woman",
                "wb_code": "SP.DYN.TFRT.IN",
                "decimals": 2,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "co2_per_capita",
                "name": "CO2 emissions per capita",
                "category": "energy",
                "unit_label": "tonnes CO2e per capita",
                "wb_code": "EN.GHG.CO2.PC.CE.AR5",
                "decimals": 2,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "renewable_electricity",
                "name": "Renewable share of electricity",
                "category": "energy",
                "unit_label": "% of total electricity output",
                "wb_code": "EG.ELC.RNEW.ZS",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "energy_intensity",
                "name": "Energy intensity of GDP",
                "category": "energy",
                "unit_label": "MJ per $2021 PPP GDP",
                "wb_code": "EG.EGY.PRIM.PP.KD",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "population",
                "name": "Population",
                "category": "geography",
                "unit_label": "people",
                "wb_code": "SP.POP.TOTL",
                "decimals": 0,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "land_area",
                "name": "Land area",
                "category": "geography",
                "unit_label": "km²",
                "wb_code": "AG.LND.TOTL.K2",
                "decimals": 0,
                "unit_prefix": "",
                "time_invariant": True,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "city_population",
                "name": "Major city populations",
                "category": "geography",
                "unit_label": "people (metro area)",
                "wb_code": None,
                "decimals": 0,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": True,
                "has_regional_aggregates": False,
            },
        ],
    },
    "tech_adoption": {
        "name": "Knowledge Base::Technology Adoption",
        "deck_id": 2026032301,
        "output": "knowledge_base_tech_adoption.apkg",
        "data_dir": "data/tech_adoption",
        "era_ranges": {
            "1990": (1988, 1992, 1990),
            "2000": (1998, 2002, 2000),
            "2010": (2008, 2012, 2010),
            "current": (2020, 2026, 2026),
        },
        "indicators": [
            {
                "id": "internet_users",
                "name": "Internet users",
                "category": "technology",
                "unit_label": "% of population",
                "wb_code": "IT.NET.USER.ZS",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "mobile_subscriptions",
                "name": "Mobile cellular subscriptions",
                "category": "technology",
                "unit_label": "per 100 people",
                "wb_code": "IT.CEL.SETS.P2",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "broadband",
                "name": "Fixed broadband subscriptions",
                "category": "technology",
                "unit_label": "per 100 people",
                "wb_code": "IT.NET.BBND.P2",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "rd_expenditure",
                "name": "R&D expenditure",
                "category": "technology",
                "unit_label": "% of GDP",
                "wb_code": "GB.XPD.RSDV.GD.ZS",
                "decimals": 2,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "hightech_exports",
                "name": "High-technology exports",
                "category": "technology",
                "unit_label": "% of manufactured exports",
                "wb_code": "TX.VAL.TECH.MF.ZS",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
            {
                "id": "electricity_access",
                "name": "Electricity access",
                "category": "technology",
                "unit_label": "% of population",
                "wb_code": "EG.ELC.ACCS.ZS",
                "decimals": 1,
                "unit_prefix": "",
                "time_invariant": False,
                "current_only": False,
                "has_regional_aggregates": True,
            },
        ],
    },
}
